version: '3'

services:
  web:
    build: .
    container_name: smart-home--server
    command: npm run dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000/tcp"
      - "3000:3000/udp"
    environment:
      - NODE_ENV=development
    depends_on:
      - smart-home--mongodb-0
      - smart-home--mongodb-1
      - smart-home--mongodb-2
      - mongoclient
    networks:
      - app-network

  smart-home--mongodb-2:
    hostname: smart-home--mongodb-2
    container_name: smart-home--mongodb-2
    image: mongo:3.6
    ports:
      - 27019:27017
    restart: always
    volumes:
      - ./docker/mongo/data/db-2:/data/db
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0", "--journal","--smallfiles" ]
    environment:
      - AUTH=no
    networks:
      - app-network

  smart-home--mongodb-1:
    hostname: smart-home--mongodb-1
    container_name: smart-home--mongodb-1
    image: mongo:3.6
    ports:
      - 27018:27017
    restart: always
    volumes:
      - ./docker/mongo/data/db-1:/data/db
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0", "--journal","--smallfiles" ]
    environment:
      - AUTH=no
    networks:
      - app-network

  smart-home--mongodb-0:
    hostname: smart-home--mongodb-0
    container_name: smart-home--mongodb-0
    image: mongo:3.6
    ports:
      - 27017:27017
    restart: always
    volumes:
      - ./docker/mongo/data/db-0:/data/db
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0", "--journal","--smallfiles" ]
    environment:
      - AUTH=no
    links:
      - smart-home--mongodb-1:smart-home--mongodb-1
      - smart-home--mongodb-2:smart-home--mongodb-2
    networks:
      - app-network

  mongoclient:
    image: mongo
    networks:
      - app-network
    depends_on:
      - smart-home--mongodb-0
      - smart-home--mongodb-1
      - smart-home--mongodb-2
    volumes:
      - ./deployment_scripts:/deployment_scripts
    entrypoint:
      - /deployment_scripts/setup.sh

networks:
  app-network:
    driver: bridge

#  config={"_id":"rs0","members":[{"_id":0,"host":"smart-home--mongodb-0:27017"},{"_id":1,"host":"smart-home--mongodb-1:27017"},{"_id":2,"host":"smart-home--mongodb-2:27017"}]}
# rs.initiate(config)
