version: "2"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
  mongo:
    image: mongo:3.4
    container_name: "mongodb-smart-home"
    ports:
      - "27017:27017"
    volumes:
      - data-volume:/data/db
    command: mongod --smallfiles --master --logpath=/dev/null # --quiet
volumes:
  data-volume:
